Milestone 3: Game Logic
imahnama/Tic-tac-toe pull request #4
Opened 2020-04-28 12:46 UTC by Phylis05

## In this Milestone we:
- Created branch game_logic
- Added logic to the game and got rid of inline comments
- Created different classes for different parts of the game logic
- Introduced attr_readers in our classes

2020-04-28 16:55 UTC, maelfosso requested changes
# changes required :red_circle: 

Hello @Phylis05 @imahnama 

It's working :+1: 
However, there are some issues related to the SOLID principle.
Please, read the comments below.

Kindly make the suggested changes and submit a new code review request.
Thanks

Mael FOSSO

2020-04-28 16:55 UTC, maelfosso commented on lib/board.rb
> +  end
No `puts/gets` in classe

2020-04-28 16:55 UTC, maelfosso commented on lib/board.rb
> +  def board_update(_board, choice, player)
why `_board` parameter?

2020-04-28 16:55 UTC, maelfosso commented on lib/game.rb
> +class Player
The file name should be identic to the class name.

2020-04-28 16:55 UTC, maelfosso commented on lib/game.rb
> +  end
Move it into the `Board` class

2020-04-28 16:55 UTC, maelfosso commented on bin/main.rb
> +  board.board_update(board, player_pos, current_player.chip)
`board` parameter is not needed

2020-04-28 16:55 UTC, maelfosso commented on bin/main.rb
> +  if current_player.wins?(player_pos)
why not, instead of `current_player.wins?` you called something like `board.winner(player_pos)`

2020-04-28 16:55 UTC, maelfosso commented on bin/main.rb
> +  current_player = current_player == player_one ? player_two : player_one
Move it as a method into the `Board` class
```ruby
def switch_player
   ....
end
```
and call `board.switch_player`

2020-04-28 16:55 UTC, maelfosso commented on bin/main.rb
>    count += 1
It will also be great to move counter into a method of `Board` class

2020-04-29 20:46 UTC, kobiyoyo requested changes
## Hi Team     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, Just few things to work on. 
### General
- [x] The game isn't working properly, it stops after three input

![1](https://user-images.githubusercontent.com/23278161/80645007-74d89300-8a62-11ea-86a2-60d535aee1d5.png)
- [x] Lets write a method for when there is a draw between both players
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-05-01 09:57 UTC, whiz25 approved these changes
## Congz team :clap:
You have made all the requested changes and your game works as required by the requirements. It's a :+1: from me. Merge and proceed to the next milestone.

### Martin Afani

2020-05-01 10:40 UTC, merged